# Use Open JDK
FROM openjdk:21-jdk-slim

# Set Env variable
ENV APP_HOME=/app
WORKDIR $APP_HOME

# Copy JAR
COPY target/hello-ci-cd-0.0.1-SNAPSHOT.jar app.jar

# Run app
ENTRYPOINT [ "java", "-jar", "app.jar" ]