name: CI PipeLine

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up JDk 17
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17 
                  
            - name: Build with Maven
              run: mvn clean install

            - name: Run test
              run: mvn test
            - name: Archive test reports
              if: always()  # run even if tests fail
              uses: actions/upload-artifact@v4
              with:
                name: surefire-reports
                path: target/surefire-reports
